FROM centos
MAINTAINER "www.svipc.com"
ENV REFRESHED_AT 2015-09-15

RUN yum upgrade -y && \
	yum -y install wget	&& \
	mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && \
	wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
	wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo

RUN yum clean all
	
ENV JAVA_HOME /usr/java/jdk1.8.0_60
ENV JRE_HOME $JAVA_HOME/jre
ENV CATALINA_HOME /home/tomcat-8.0.9
	
RUN wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
	http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm && \
	rpm -ivh jdk-8u60-linux-x64.rpm && \
	rm -rf jdk-8u60-linux-x64.rpm

RUN wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.9/bin/apache-tomcat-8.0.9.tar.gz && \
	tar -zxvf apache-tomcat-8.0.9.tar.gz && \
	rm -rf apache-tomcat*.tar.gz && \
	mv apache-tomcat* ${CATALINA_HOME} 
	
RUN chmod +x ${CATALINA_HOME}/bin/*sh

EXPOSE 8080

CMD ["/home/tomcat-8.0.9/bin/startup.sh"]