FROM centos
MAINTAINER "www.svipc.com"
ENV REFRESHED_AT 2015-09-18

RUN yum -y install wget && \
	mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && \
	wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
	wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo && \
	rpm -ivh http://mirrors.aliyun.com/epel/epel-release-latest-7.noarch.rpm && \
	yum upgrade -y && \
	yum install -y make && \
	yum install -y gcc && \
	yum install -y jemalloc.x86_64 && \
	yum install -y jemalloc-devel.x86_64 && \
	yum clean all

RUN cd /usr/ && \
	wget https://sourceforge.net/projects/levent/files/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz && \
	tar zxvf libevent-2.0.22-stable.tar.gz && \
	rm -rf libevent-2.0.22-stable.tar.gz && \
	cd libevent-2.0.22-stable && \
	./configure && \
	make && make install && \
	ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib64/libevent-2.0.so.5

RUN cd /usr/local/ && \
	wget http://memcached.org/files/memcached-1.4.24.tar.gz && \
	tar zxvf memcached-1.4.24.tar.gz && \
	rm -rf memcached-1.4.24.tar.gz && \
	cd memcached-1.4.24/ && \
	./configure && \
	make && \
	make install
	
EXPOSE 11211

CMD ["memcached -d -m 64 -p 11211 -u root"]