FROM centos
MAINTAINER "www.svipc.com"
ENV REFRESHED_AT 2015-09-18

RUN yum -y install wget && \
	mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && \
	wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
	wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo && \
	yum upgrade -y && \
	yum clean all

RUN yum -y install subversion subversion-tools  && \
	mkdir /home/svn
	
VOLUME /home/svn
	
EXPOSE 3690

CMD ["svnserve", "--foreground", "-d", "-r", "/home/svn"]