FROM centos
MAINTAINER "www.svipc.com"
ENV REFRESHED_AT 2015-09-18

RUN yum -y install wget && \
	mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup && \
	wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
	wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo && \
	rpm -ivh http://mirrors.aliyun.com/epel/epel-release-latest-7.noarch.rpm && \
	yum upgrade -y && \
	yum install -y make && \
	yum install -y gcc && \
	yum install -y jemalloc.x86_64 && \
	yum install -y jemalloc-devel.x86_64 && \
	yum clean all

RUN cd /home/ \
	&& wget http://download.redis.io/releases/redis-3.0.4.tar.gz \
	&& tar zxvf redis-3.0.4.tar.gz \
	&& rm -rf redis-3.0.4.tar.gz \
	&& cd redis-3.0.4/deps/ \
	&& make hiredis lua\
	&& cd jemalloc;./configure;make;cd ../..\
	&& make \
	&& make install

EXPOSE 6379

CMD ["/home/redis-3.0.4/src/redis-server", "/home/redis-3.0.4/redis.conf"]